const menu = document.querySelector('.menu');
menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') !== 'true'; menu.setAttribute('aria-expanded', String(open)); menu.setAttribute('aria-label', open ? 'Cerrar menú' : 'Abrir menú'); document.querySelector('nav').classList.toggle('open', open); });
document.querySelectorAll('nav a').forEach(a => a.addEventListener('click', () => {menu.setAttribute('aria-expanded', 'false');menu.setAttribute('aria-label','Abrir menú');document.querySelector('nav').classList.remove('open');}));
const details = {
portete: ['Isla Portete, sin prisa', 'Una playa para contemplar el mar y disfrutar del paisaje costero. Organiza tu visita con información local sobre accesos y transporte. Confirma las condiciones del día antes de salir.\n\nLleva agua, protección solar y regresa con todos tus residuos.', 'Isla Portete Ecuador'],
mompiche: ['Mompiche, al ritmo del mar', 'Un destino de playa en el cantón Muisne, en la costa de Esmeraldas. Recorre su entorno, conoce sus sabores y disfruta de una pausa junto al mar.\n\nSi buscas actividades acuáticas, consulta a operadores locales sobre condiciones, equipo y disponibilidad.', 'Mompiche Ecuador'],
muisne: ['Muisne, esencia esmeraldeña', 'Playas, paisajes costeros y cocina local forman parte de este destino de Esmeraldas. Una invitación a descubrir el territorio con respeto por sus comunidades y su entorno.\n\nConsulta rutas, transporte y condiciones de acceso antes de organizar tu recorrido.', 'Muisne Ecuador'],
sabores: ['Sabores de la costa', 'La cocina esmeraldeña invita a descubrir preparaciones con coco, pescados y mariscos. Pregunta en los establecimientos locales qué está disponible y qué recomiendan para ese día.\n\nConfirma ingredientes, horarios y precios directamente con cada negocio.', 'Restaurantes Muisne Ecuador'],
negocios: ['Crezcamos desde lo local', 'Mangle está preparando su selección de negocios aliados. El canal de inscripción todavía no está habilitado.\n\nPara tu futura ficha, prepara el nombre del negocio, una descripción, la zona, fotografías propias y un contacto comercial autorizado. Publicaremos información confirmada por cada negocio.', null],
Experiencias: ['Experiencias con sabor a costa', 'Explora los paisajes de Mompiche, una escapada a Portete o un recorrido por Muisne. Para surf, paseos y actividades guiadas, confirma las condiciones y disponibilidad con prestadores locales.', 'Mompiche Ecuador'],
Gastronomía: ['Encuentra un sabor local', 'Descubre la cocina esmeraldeña y pregunta por las preparaciones del día. Confirma horarios, ingredientes y precios con el establecimiento.', 'Restaurantes Mompiche Ecuador'],
Hospedaje: ['Tu pausa junto al mar', 'Busca un alojamiento en Mompiche o los alrededores de Muisne según tu forma de viajar. Antes de reservar, confirma ubicación, servicios, accesibilidad, condiciones y tarifa con el hospedaje. Mangle aún no tiene alojamientos aliados publicados.', 'Hospedajes Mompiche Ecuador'],
Lugares: ['Rincones para descubrir', 'Mompiche, Isla Portete y Muisne son puntos de partida para explorar la costa de Esmeraldas. Consulta las condiciones locales de transporte y acceso para preparar tu visita.', 'Muisne Ecuador']
};
const dialog = document.querySelector('#detail');
function showDetail(key) {const data=details[key];if(!data)return;document.querySelector('#detail-title').textContent=data[0];document.querySelector('#detail-body').textContent=data[1];const map=document.querySelector('#detail-map');map.hidden=!data[2];map.style.display=data[2]?'inline-flex':'none';if(data[2])map.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(data[2]);dialog.showModal();}
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>showDetail(b.dataset.detail)));
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>showDetail(b.dataset.category)));
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const plans={playa:'Tu punto de partida: Isla Portete. Planea una pausa junto al mar y confirma accesos y transporte con información local.',comida:'Tu punto de partida: la cocina esmeraldeña en Muisne. Pregunta por preparaciones con coco y por las opciones disponibles hoy.',naturaleza:'Tu punto de partida: un recorrido por los paisajes costeros de Muisne. Consulta las rutas y condiciones locales antes de salir.',hospedaje:'Tu punto de partida: explorar alojamientos en Mompiche. Compara ubicación y servicios, y confirma disponibilidad y tarifas directamente.'};
document.querySelector('#plan-form').addEventListener('submit',e=>{e.preventDefault();const result=document.querySelector('#plan-result');result.hidden=false;result.textContent=plans[document.querySelector('#interest').value];});
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('.today-date').textContent=new Intl.DateTimeFormat('es-EC',{weekday:'long',day:'numeric',month:'long',timeZone:'America/Guayaquil'}).format(new Date());

